<?php
 $aik =  array (
  'sitename' => 'Coco视频',
  'pcdomain' => 'http://www.cocogo.xyz',
  'title' => 'Coco视频',
  'keywords' => 'Coco, 可可, 影院, 免费, VIP, 破解, 电影, ',
  'description' => '免VIP抢先观看最新好看的电影和电视剧',
  'homelink' => '',
  'icp' => '闽ICP备17026396号-2',
  'foot' => '本站提供的最新电影和电视剧资源均系收集于各大视频网站,本站只提供web页面服务,并不提供影片资源存储,也不参与录制、上传。若本站收录的节目无意侵犯了贵司版权，请告知，我们会及时处理和回复,谢谢。',
  'tongji' => '',
  'changyan' => '',
  'youlian' => '',
     'jiekou1' => 'http://jx.sw8.top/?url=',
     'jiekou2' => 'https://yun.jxegc.com/vip.php?url=',	//酷云资源
     'jiekou3' => 'http://2gty.com/apiurl/yun.php?url=',
     'jiekou4' => 'http://jx.lyang.xin/?url=',
     'jiekou5' => 'http://cn.bjbanshan.cn/jiexi.php?url=',	//517
     'jiekou6' => 'http://jiexi.071811.cc/jx2.php?url=',	//思古解析1
     'jiekou7' => 'http://zj88888.cc/jx/?url=',	//思古解析2
     'jiekou8' => 'http://api.bbbbbb.me/vip/?url=',
     'jiekou9' => 'http://www.ibb6.com/jiexi/?url=',
     'jiekou10' =>'http://api.bbbbbb.me/svip/v.php?url=',
     'admin_name' => 'admin',
  'admin_pass' => '9d7f5e4b6d9f93b20ca8aa96007dba03',
  'admin_email' => '766283550@qq.com',
  'logo_dh' => '<img src="images/logo.png">',
  'logo_ss' => '<img style="width:25rem;" id="imgsrc" src="images/sologo.png">',
  'movie_ad' => '<a href="http://www.shopcoco.top"><img id="imgsrc" src="images/tianmao2.png"></a>',
  'tv_ad' => '<a href="http://www.shopcoco.top"><img id="imgsrc" src="images/tianmao4.png"></a>',
  'zongyi_ad' => '<a href="http://www.shopcoco.top"><img id="imgsrc" src="images/tianmao3.png"></a>',
  'dongman_ad' => '<a href="http://www.shopcoco.top"><img id="imgsrc" src="images/tianmao3.png"></a>',
  'bofang_ad' => '',
  'jiazai_ad' => '',
  'dbts' => '',
  'zfb_ad' => '<img src="images/zfb.png">',
  'wx_ad' => '<img src="images/wx.png">',
  'cebian3_ad' => '<a class="style02"><strong>扫一扫或分享二维码</strong><div class="article-wechats"> </br> <img src="images/wx.png"></div> </a>',
  'cebian2_ad' => '<a class="style02" href="http://www.shopcoco.top" target="_blank"><strong>可可淘券网</strong><img src="images/tianmao1.jpg"></a>',
  'cebian1_ad' => '<a class="style02"><img src="images/saoma.png"></a>',
  'cebian4_ad' => '',
  'top1_ad' => '',
  'top2_ad' => '',
  'top_ad' => '',
  'weixin_ad' => '',
  'end_ad' => '',
  'hometopnotice' => '',
  'hometopright' => '',
  'sort' => '1,2,3,4,5,6,7,8,9,10',
  'joinhotkey' => '0',
);
?>